import { useEffect, useState } from 'react'
import Marquee from 'react-fast-marquee'
import Button from '@mui/material/Button'
import Box from '@mui/material/Box'
import Head from 'next/head'
import Image from 'next/image'
import CancelIcon from '@mui/icons-material/Cancel'
import clsx from 'clsx'

import * as strapiApiService from '@/services/strapiApi.service'
import Footer from './Footer'
import FooterNavigation from './FooterNavigation'
import Header from './Header'
import { AnnouncementAttributesData } from '@/types/announcement.type'
import { StrapiDataItem } from '@/types/strapi.type'
import { useRouter } from 'next/router'

interface LayoutProps {
  children?: React.ReactNode
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  const [announcement, setAnnouncement] =
    useState<StrapiDataItem<AnnouncementAttributesData>>()
  const [visibleLineButton, setVisibleLineButton] = useState(true)
  const router = useRouter()
  const { reference } = router.query
  const visibleNavigation = reference !== '11' && reference !== '12'
  const keywords = [
    'bonusgame168',
    'bonus',
    'bonusgame',
    'game168',
    'bonus168',
    '168',
    'เว็บสล็อต',
    'สล็อตออนไลน์',
    'เกมสล็อตออนไลน์ได้เงินจริง',
    'PGSLOT',
    'คาสิโน',
    'คาสิโนออนไลน์',
    'casino',
    'บาคาร่า',
    'เว็บแทงบอลออนไลน์',
    'ยูฟ่า',
    'UFA',
    'พนันออนไลน์',
    'บริการตลอด 24 ชม',
    'หวย',
    'slot',
    'slot online',
    'game slot',
    'gameslot',
    'สล็อต',
    'สล็อตออนไลน์',
    'เกมสล็อต',
    'ยิงปลา',
    'เกมยิงปลา',
    'joker',
    'evoplay',
    'simpleplay',
    'playstar',
    'kingmaker',
    'habanero',
    'sexygame',
    'sbobet',
    'evoplay',
    'wm casino',
    'amb poker',
    'pgslot',
    'jokergaming',
    'sagame',
    'dream gaming',
    'แทงบอล',
    'เดิมพันกีฬา',
    'london1688',
    'คาสิโนออนไลน์',
    'บาคาร่าออนไลน์',
    'บาคาร่า',
    'คาสิโนสด',
    'คาสิโนออนไลน์',
    'เสือสังกร',
    'ไฺฮโล',
    'รูเล็ต',
    'สล็อตออนไลน์',
    'เกมส์สล็อตออนไลน์',
    'สล็อต',
    'เกมสล็อต',
    'กำถั่ว',
    'slot ออนไลน์',
    'slot online',
    'live คาสิโน',
    'คาสิโน auto ฝากถอน',
    'เล่นคาสิโนออนไลน์',
    'casino sagame',
    'casino sagaming',
  ]
  const description =
    'เล่นสล็อตออนไลน์เว็บตรง แจกจริงไม่มีอั้นกับโปรโมชั่น เครดิตฟรี 100 ล่าสุด แค่สมัครสมาชิกวันนี้ก็รับได้เลยทันที โปรสล็อตสมาชิกใหม่มาพร้อมกับเกมฮิตที่กำลังมาแรงเป็นอย่างมากในปี 2023  รับรองเลยว่าจะต้องถูกใจหลายๆ คนอย่างแน่นอน, สล็อตเว็บตรง บริการเกมสล็อต เว็บตรงไม่ผ่านเอเย่นต์ สัมผัสประสบการเล่นสล็อตแตกหนักกับเรา ฝาก ถอน ไม่มีขั้นต่ำ เล่นสล็อต เว็บใหญ่ PGคาสิโนออนไลน์อันดับ1 สล็อตเว็บตรงที่นักพนันต่างรู้ เว็บสล็อต168 ที่แตกหนัก แจกจริง สมชื่อเฮงจริง นึกถึงสล็อตออนไลน์ต้อง, แทงหวยออนไลน์ เว็บไซต์อันดับ 1 จ่ายเยอะสุด ถอนเงินไว ไม่รอนาน มีทั้งหวยรัฐบาล หวยลาว หวยหุ้น หวยฮานอย หาเว็บแทงหวย ซื้อหวยออนไลน์ นึกถึงเรา'
  const title =
    'BONUS GAME168 เว็บสล็อตอันดับ 1 ระบบออโต้ รวดเร็ว ทันใจ ฝาก-ถอน โอนไว สล็อตออนไลน์ สล็อตแตกง่ายที่นี่'

  useEffect(() => {
    strapiApiService
      .getAnnouncement()
      .then((response) => {
        setAnnouncement(response.data)
      })
      .catch(() => {})
  }, [])

  const handleClickHiddenLineButton = () => {
    setVisibleLineButton(false)
  }

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <meta property='og:locale' content='th_TH' />
        <meta name='keywords' content={keywords.join(',')} />
        <meta name='description' content={description} />
        {/* facebook */}
        <meta property='og:site_name' content='BonusGame168' />
        <meta property='og:title' content={title} />
        <meta property='og:description' content={description} />
        <meta property='og:url' content='https://bonusgame168.com/' />
        <meta property='og:type' content='website' />
        {/* twitter */}
        <meta name='twitter:card' content='summary_large_image' />
        <meta name='twitter:title' content={title} />
        <meta name='twitter:description' content={description} />
      </Head>
      {visibleNavigation && <Header />}
      {announcement && (
        <div
          className={clsx(
            'w-full text-white text-xs xl:text-lg bg-[#170023] py-2 sticky z-[99]',
            {
              'top-[var(--header-height)]': visibleNavigation,
              'top-0': !visibleNavigation,
            }
          )}
        >
          <Marquee speed={50} gradient={false}>
            {announcement.attributes.title}
          </Marquee>
        </div>
      )}
      <main>{children}</main>
      {visibleNavigation && visibleLineButton && (
        <Box
          className='fixed top-[60%] md:top-[70%] right-0 z-50'
          sx={{ p: 2 }}
        >
          <Button
            aria-label='hidden line button'
            variant='text'
            color='error'
            className='absolute right-0 z-10 top-[-15px] p-0'
            onClick={() => handleClickHiddenLineButton()}
          >
            <CancelIcon />
          </Button>
          <a
            href='https://line.me/R/ti/p/@147hdwat'
            target='_blank'
            rel='noreferrer'
          >
            <Image
              src='/images/ic-line-overlay.webp'
              alt='line button'
              width={93}
              height={131}
              priority
            />
          </a>
        </Box>
      )}
      <Footer />
      {visibleNavigation && <FooterNavigation />}
    </>
  )
}

export default Layout
